CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE outbox (
                        id UUID PRIMARY KEY,
                        aggregateid TEXT NOT NULL,
                        aggregatetype TEXT NOT NULL,
                        type TEXT NOT NULL,
                        payload JSONB
);
CREATE TABLE games (
                       id BIGINT generated by default as identity NOT NULL PRIMARY KEY,
                       entity_id BIGINT NOT NULL UNIQUE,
                       name TEXT NOT NULL,
                       summary TEXT,
                       url TEXT,
                       release_date DATE
);